spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT
    hikari:
      username: root
      password: 110308
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos 地址
        server-addr: localhost:8848
        #指定命名空间
#        namespace: 425aad9e-d192-414d-8fc3-33c81e4574d6
        #指定集群名称
#        cluster-name: XJ
        #元数据写入nacos
#        metadata:
#          hhh: a
#          fff: b
  application:
    # 服务名称用- 不要用_ 不要用特殊字符
    name: user-center

server:
  port: 8081
